- name: Update and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Install Nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present
  notify:
   - Start Nginx

- name: Copy config
  ansible.builtin.copy:
    src: h5bp
    dest: /etc/nginx
    owner: root
    group: root

- name: Disable default site
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- include: local-page.yml
- include: proxied.yml
    
- name: All web permissions
  ansible.builtin.file:
    dest: '{{ item }}'
    mode: u=rx,g=rx,o=rx
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  notify:
    - Restart Ngingx
  with_fileglob:
    - "/var/www/*"
