- name: Update and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow http
  community.general.ufw:
    rule: allow
    port: 80 # Did not let me use http profile

- name: Install Nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present
  notify:
   - Start Nginx

- name: Copy config
  ansible.builtin.copy:
    src: h5bp
    dest: /etc/nginx
    owner: root
    group: root

- name: Disable default site
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- include_tasks: local_page.yml
- include_tasks: apps_config.yml
    
- name: All web permissions
  ansible.builtin.file:
    dest: '{{ item }}'
    mode: u=rx,g=rx,o=rx
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  notify:
    - Restart Ngingx
  with_fileglob:
    - "/var/www/*"
