- name: Update and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install Nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present
  notify:
   - Start Nginx

- name: Copy config
  ansible.builtin.copy:
    src: h5bp
    dest: /etc/nginx
    owner: root
    group: root

- name: Disable default site
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent


- include_tasks: local_page.yml
# - include_tasks: apps_config.yml
    
    
- name: Find all files in var/www
  ansible.builtin.command: >-
    find /var/www/ -path /var/www/html -prune -o -type f,d -print
  register: www_files

- name: All web permissions
  ansible.builtin.file:
    dest: '{{ item }}'
    mode: u=rx,g=rx,o=rx
    owner: www-data
    group: www-data
  notify:
    - Restart Nginx
  loop: "{{ www_files.stdout_lines }}"