- name: Update and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install necessary stuff
  ansible.builtin.apt:
    pkg: 
      - nginx
      - acl
    state: present
  notify:
   - Start Nginx


- include_tasks: nginx_config.yml
- include_tasks: static_files.yml


- name: Find all files in var/log/nginx
  ansible.builtin.command: >-
    find /var/log/nginx
  register: log_files

- name: All log file permissions
  ansible.builtin.file:
    dest: '{{ item }}'
    mode: u=rw,g=rw,o=r
    owner: www-data
    group: www-data
  notify:
    - Restart Nginx
  loop: "{{ log_files.stdout_lines }}"