- name: Create local page folder
  ansible.builtin.file:
    dest: '/var/www/{{ local_page_domain }}/public'
    state: directory
  when: not ansible_check_mode

- name: Copy the HTML file
  ansible.builtin.copy:
    src: local-page.html
    dest: '/var/www/{{ local_page_domain }}/public/index.html'
    mode: u=rx,g=rx,o=rx
    owner: www-data
    group: www-data

- name: Find all files in var/www
  ansible.builtin.command: >-
    find /var/www/ -path /var/www/html -prune -o -print -type f,d
  register: www_files

- name: All web permissions
  ansible.builtin.file:
    dest: '{{ item }}'
    mode: u=rx,g=rx,o=rx
    owner: www-data
    group: www-data
  notify:
    - Restart Nginx
  loop: "{{ www_files.stdout_lines }}"