---
- hosts: proxy_host
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: proxy_server
      vars:
        - python_app_ip: 192.168.56.11
        - python_app_port: 7523
        - golang_app_ip: 192.168.56.11
        - golang_app_port: 2213
            
- hosts: app_host
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: app_server
      vars:
        - python_app_port: 7523
        - golang_app_port: 2213