---
# defaults file for app_server
# The target data for the apps in the system. Domains are for the hosts file
python_app_domain: python.local
python_app_port: '4322'
python_app_user: alchemist
python_app_folder: "/opt/flask_app"
python_app_folder_venv: '{{ python_app_folder }}/venv'
python_app_requirements: "python_flask/requirements.txt"

golang_app_domain: golang.local
golang_app_port: '9403'
golang_app_user: gopher
golang_app_folder: "/opt/golang_app"


