# https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uswgi-and-nginx-on-ubuntu-18-04
- name: Update and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes



