---
- name: Install Python
  apt:
    pkg:
      - python3-pip 
      - python3-dev  
      - python3-setuptools
      - python3-venv
      - build-essential  
      - libssl-dev  
      - libffi-dev
    state: latest
    update_cache: true

# Configure virtualenv
# Install uWSGI
# Move over the Flask app