---
- hosts: proxy_host
  become: yes
  become_method: sudo
  remote_user: test
  tags: proxy_server
  roles:
    - role: proxy_server
      vars:
          python_app_ip: "app_host"
          golang_app_ip: "app_host"
          python_app_port: 9091
          golang_app_port: 9092
            
- hosts: app_host
  become: yes
  become_method: sudo
  remote_user: test
  tags: app_server
  roles:
    - role: app_server
      vars:
          python_app_port: 9091
          golang_app_port: 9092