---
# handlers file for proxy_server
 - name: Start Nginx
   ansible.builtin.service:
     name: nginx
     state: started

     
 - name: Restart Nginx
   ansible.builtin.service:
     name: nginx
     state: reloaded

