---
- name: Create group
  ansible.builtin.group:
    name: "{{ python_app_user }}"
    state: present


- name: Create user holder for the Python app
  ansible.builtin.user: 
    name: '{{ python_app_user }}'
    group: '{{ python_app_user }}'
    createhome: no

- name: Install Python
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-virtualenv
    state: latest
    update_cache: true

- name: Move Python files
  ansible.builtin.copy:
    src: python_flask/
    dest: '{{ python_app_folder }}'
    owner: '{{ python_app_user }}'
    group: '{{ python_app_user }}'

- name: Configure with the dev modules
  ansible.builtin.pip:
    requirements: '{{ python_app_folder_requirements }}'
    virtualenv: '{{ python_app_folder_venv }}'

- name: Add uWSGI to the env
  ansible.builtin.pip:
    name: uWSGI
    virtualenv: '{{ python_app_folder_venv }}'

- name: Add config for uwsgi
  ansible.builtin.template:
    src: uwsgi.ini.j2
    dest: '{{ python_app_folder }}/uwsgi.ini'
    owner: '{{ python_app_user }}'
    group: '{{ python_app_user }}'


- name: Run uWSGI
  ansible.builtin.shell: >-
    {{ python_app_folder_venv }}/bin/uwsgi {{ python_app_folder }}/uwsgi.ini &